// @vitest-environment jsdom
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';

const mockAuthFetch = vi.fn();
vi.mock('../../lib/api', () => ({
  authFetch: (...args: any[]) => mockAuthFetch(...args),
}));

vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string, fallback?: string) => {
      const map: Record<string, string> = {
        'marketing.title': 'AI Marketing Posts',
        'marketing.subtitle': 'Swipe to post',
        'marketing.prev': 'Previous post',
        'marketing.next': 'Next post',
        'marketing.copy': 'Copy to Clipboard',
        'marketing.copied': '✓ Copied',
        'marketing.shareTelegram': 'Share on Telegram',
      };
      return map[key] || fallback || key;
    },
  }),
}));

vi.mock('../../components/ui/toast-helper', () => ({
  showToast: vi.fn(),
}));

import { MarketingDeck } from '../Dashboard/MarketingDeck';

describe('MarketingDeck', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    localStorage.setItem('tenantSlug', 'test-salon');
    localStorage.setItem('tenantName', 'Test Salon');
    localStorage.setItem('tenantCategory', 'salon');
  });

  it('renders the deck title', async () => {
    mockAuthFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve([{ text: 'Post one' }]),
    });

    render(<MarketingDeck />);
    await waitFor(() => {
      expect(screen.getAllByText('AI Marketing Posts').length).toBeGreaterThan(0);
    });
  });

  it('shows loading skeletons initially', () => {
    mockAuthFetch.mockReturnValue(new Promise(() => {}));

    const { container } = render(<MarketingDeck />);
    const skeletons = container.querySelectorAll('.skeleton-wave');
    expect(skeletons.length).toBeGreaterThanOrEqual(1);
  });

  it('falls back to static text on API failure', async () => {
    mockAuthFetch.mockResolvedValue({ ok: false });

    render(<MarketingDeck />);
    await waitFor(() => {
      expect(screen.getAllByText(/Test Salon/).length).toBeGreaterThan(0);
    });
    expect(screen.getAllByText(/Addis Ababa/).length).toBeGreaterThan(0);
  });

  it('falls back to static text when API returns empty array', async () => {
    mockAuthFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve([]),
    });

    render(<MarketingDeck />);
    await waitFor(() => {
      expect(screen.getAllByText(/Test Salon/).length).toBeGreaterThan(0);
    });
  });

  it('renders AI-generated badge', async () => {
    mockAuthFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(['Hello world']),
    });

    render(<MarketingDeck />);
    await waitFor(() => {
      expect(screen.getAllByText(/Generated by Egebeya AI/).length).toBeGreaterThan(0);
    });
  });

  it('opens Telegram with correct URL-encoded text', async () => {
    mockAuthFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(['Special post text']),
    });

    const openSpy = vi.spyOn(window, 'open').mockImplementation(() => null);

    render(<MarketingDeck />);
    await waitFor(() => {
      expect(screen.getAllByText('Special post text').length).toBeGreaterThan(0);
    });

    // Click any Telegram button — StrictMode renders two, both share state
    const telegramBtns = screen.getAllByRole('button', { name: /Share on Telegram/i });
    expect(telegramBtns.length).toBeGreaterThanOrEqual(1);
    fireEvent.click(telegramBtns[telegramBtns.length - 1]);

    await waitFor(() => {
      expect(openSpy).toHaveBeenCalled();
    });
    const url = openSpy.mock.calls[openSpy.mock.calls.length - 1][0] as string;
    expect(url).toContain('https://t.me/share/url');
    expect(url).toContain('https://test-salon.egebeya.et');
    expect(url).toContain(encodeURIComponent('Special post text'));

    openSpy.mockRestore();
  });

  it('copies text to clipboard on copy button click', async () => {
    mockAuthFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(['Copy me']),
    });

    const writeTextMock = vi.fn().mockResolvedValue(undefined);
    Object.assign(navigator, { clipboard: { writeText: writeTextMock } });

    render(<MarketingDeck />);
    await waitFor(() => {
      expect(screen.getAllByText('Copy me').length).toBeGreaterThan(0);
    });

    const copyBtns = screen.getAllByRole('button', { name: /Copy to Clipboard/i });
    expect(copyBtns.length).toBeGreaterThanOrEqual(1);
    fireEvent.click(copyBtns[copyBtns.length - 1]);

    await waitFor(() => {
      expect(writeTextMock).toHaveBeenCalledWith('Copy me');
    });
  });

  it('navigates between posts with arrow buttons', async () => {
    mockAuthFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(['Post A', 'Post B', 'Post C']),
    });

    render(<MarketingDeck />);
    await waitFor(() => {
      expect(screen.getAllByText('Post A').length).toBeGreaterThan(0);
    });

    const nextBtn = screen.getByRole('button', { name: /Next post/i });
    fireEvent.click(nextBtn);

    await waitFor(() => {
      expect(screen.getAllByText('Post B').length).toBeGreaterThan(0);
    });
  });
});
