// @vitest-environment jsdom
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, waitFor, cleanup } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';

const mockAuthFetch = vi.fn();
vi.mock('../../lib/api', () => ({
  authFetch: (...args: any[]) => mockAuthFetch(...args),
}));

vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    i18n: { language: 'en' },
    t: (key: string, fallback?: string) => fallback || key,
  }),
}));

const mockToast = vi.fn();
vi.mock('../../components/ui/toast-helper', () => ({
  showToast: (...args: any[]) => mockToast(...args),
}));

import { MarketingDeck } from '../Dashboard/MarketingDeck';

function mockOwnerMeta(snippetImpl?: (body: any) => any) {
  mockAuthFetch.mockImplementation(async (url: string, init?: any) => {
    if (url === '/api/tenant/settings') {
      return { ok: true, json: async () => ({ category: 'salon' }) } as any;
    }
    if (url === '/api/tenant/services') {
      return { ok: true, json: async () => [{ name: 'Haircut' }, { name: 'Color' }] } as any;
    }
    if (url === '/api/tenant/ai/marketing-snippet') {
      if (!snippetImpl) return { ok: false, json: async () => ({}) } as any;
      return snippetImpl(JSON.parse(init.body)) as any;
    }
    return { ok: false, json: async () => ({}) } as any;
  });
}

describe('MarketingDeck (#48 — honest AI badge)', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    localStorage.setItem('tenantSlug', 'test-salon');
  });

  afterEach(cleanup);

  it('renders the template suggestion visibly as a template, never with the AI badge', async () => {
    mockOwnerMeta();

    render(<MarketingDeck businessName="Test Salon" />);

    const card = await screen.findByText(/Discover Test Salon/);
    expect(card).toBeTruthy();
    expect(screen.getByTestId('badge-template')).toHaveTextContent('Template suggestion');
    expect(screen.queryByTestId('badge-ai')).toBeNull();
    expect(screen.queryByText(/Generated by Egebeya AI/)).toBeNull();

    // The phantom GET /ai/weekly-posts route is gone from the deck forever.
    expect(mockAuthFetch.mock.calls.some((c) => String(c[0]).includes('weekly-posts'))).toBe(false);
  });

  it('✨ badge appears only after the AI route actually generates text', async () => {
    mockOwnerMeta((body) => {
      expect(body).toMatchObject({
        businessName: 'Test Salon',
        category: 'salon',
        services: ['Haircut', 'Color'],
        locale: 'en',
      });
      return { ok: true, json: async () => ({ snippet: 'Fresh AI-written post', locale: 'en' }) };
    });

    render(<MarketingDeck businessName="Test Salon" />);
    await screen.findByText(/Discover Test Salon/);

    fireEvent.click(screen.getByTestId('generate-ai-btn'));

    expect(await screen.findByText('Fresh AI-written post')).toBeTruthy();
    expect(screen.getByTestId('badge-ai')).toHaveTextContent('Generated by Egebeya AI');
    expect(mockAuthFetch).toHaveBeenCalledWith(
      '/api/tenant/ai/marketing-snippet',
      expect.objectContaining({ method: 'POST' }),
    );
  });

  it('403 AI_CONSENT_REQUIRED toasts honestly and no AI post or badge appears', async () => {
    mockOwnerMeta(() => ({
      ok: false,
      status: 403,
      json: async () => ({ error: 'consent', code: 'AI_CONSENT_REQUIRED' }),
    }));

    render(<MarketingDeck businessName="Test Salon" />);
    await screen.findByText(/Discover Test Salon/);

    fireEvent.click(screen.getByTestId('generate-ai-btn'));

    await waitFor(() => {
      expect(mockToast).toHaveBeenCalledWith(
        'AI consent required',
        expect.anything(),
        'destructive',
      );
    });
    expect(screen.queryByTestId('badge-ai')).toBeNull();
    expect(screen.getByTestId('badge-template')).toBeTruthy();
  });

  it('provenance follows the current post when navigating', async () => {
    mockOwnerMeta(() => ({ ok: true, json: async () => ({ snippet: 'AI text here' }) }));

    render(<MarketingDeck businessName="Test Salon" />);
    await screen.findByText(/Discover Test Salon/);
    fireEvent.click(screen.getByTestId('generate-ai-btn'));
    await screen.findByText('AI text here');

    // Two posts now: AI (index 0, ✨) and template. Arrow switches the badge.
    expect(screen.getByTestId('badge-ai')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: /Next post/i }));
    await waitFor(() => {
      expect(screen.getByTestId('badge-template')).toBeTruthy();
      expect(screen.queryByTestId('badge-ai')).toBeNull();
    });
  });
});
